# Generated by Django 5.2.7 on 2025-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carta', models.CharField(max_length=100)),
                ('rareza', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=50)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_expansion', models.CharField(max_length=20)),
            ],
        ),
    ]
